version: "3.1"
services:
    client:
        build: ./client
        container_name: client
        ports:
            - "3000:3000"
        env_file:
            - ./client/.env.local
    server:
        build: ./server
        container_name: server
        env_file:
            - ./server/.env
        ports:
            - "8000:8000"
