version: "3.1"
services:
    client:
        build: ./client
        container_name: client
        ports:
            - "3000:3000"
        environment:
            - NEXT_PUBLIC_API_URL=https://vibewave.live/api
    server:
        build: ./server
        container_name: server
        env_file:
            - ./server/.env
        ports:
            - "8000:8000"
