version: "3.1"
services:
    client:
        build: ./client
        container_name: client
        ports:
            - "80:80"
    server:
        build: ./server
        container_name: server
        env_file:
            - ./server/.env
        ports:
            - "8000:8000"
